# Generated by Django 3.1.2 on 2020-12-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=250)),
                ('first_content', models.TextField()),
                ('first_image', models.ImageField(upload_to='card-images/')),
                ('second_content', models.TextField()),
                ('sliders', models.ManyToManyField(blank=True, to='website.SliderImage')),
            ],
        ),
    ]
